# Use the official Node.js 16 Alpine image
FROM node:16-alpine 
# Set the working directory to /app
WORKDIR /app
# Copy the current directory contents into the working directory
COPY . . 
# Install all dependencies
RUN npm install 
# Build the application
RUN npm run build 
# Remove the development dependencies
RUN rm -rf node_modules 
# Install only the production dependencies
RUN npm install --production 
# Run the application 
CMD [ "npm", "run","start" ] 